In [31]:
import pandas as pd
import numpy as np
import os

os.chdir('d:/Libraries/Documents/BAN 5743')

In [32]:
df = pd.read_excel('travel_times_hours.xlsx', index_col=None, header=None)
# print(df.head())

m2 = df.to_numpy()
print(m2)

[[0.         0.55       0.56666667 ... 0.65       0.9        0.33333333]
 [0.48333333 0.         0.23333333 ... 0.36666667 0.55       0.6       ]
 [0.51666667 0.25       0.         ... 0.36666667 0.6        0.63333333]
 ...
 [0.56666667 0.33333333 0.31666667 ... 0.         0.4        0.58333333]
 [0.81666667 0.56666667 0.6        ... 0.4        0.         0.93333333]
 [0.36666667 0.63333333 0.63333333 ... 0.63333333 0.93333333 0.        ]]


In [33]:
df = pd.read_excel('location_mapping.xlsx', index_col=None)
# print(df.head())

m1 = df.to_numpy()
print(m1)

[[8.4200e+02 3.3680e+00 0.0000e+00]
 [2.8910e+03 1.1564e+01 0.0000e+00]
 [3.0920e+03 1.2368e+01 0.0000e+00]
 [1.4850e+03 5.9400e+00 0.0000e+00]
 [1.6790e+03 6.7160e+00 0.0000e+00]
 [1.6630e+03 6.6520e+00 0.0000e+00]
 [8.7400e+02 3.4960e+00 0.0000e+00]
 [2.6310e+03 1.0524e+01 0.0000e+00]
 [1.0180e+03 4.0720e+00 0.0000e+00]
 [7.4500e+02 2.9800e+00 0.0000e+00]
 [1.4890e+03 5.9560e+00 0.0000e+00]
 [1.0563e+04 4.2252e+01 0.0000e+00]
 [1.5970e+03 6.3880e+00 0.0000e+00]
 [2.6180e+03 1.0472e+01 0.0000e+00]
 [8.8200e+02 3.5280e+00 0.0000e+00]
 [7.5200e+02 3.0080e+00 0.0000e+00]
 [2.8260e+03 1.1304e+01 0.0000e+00]
 [9.5800e+02 3.8320e+00 0.0000e+00]
 [1.8810e+03 7.5240e+00 0.0000e+00]
 [9.0240e+03 3.6096e+01 0.0000e+00]
 [1.0186e+04 4.0744e+01 0.0000e+00]
 [2.9700e+03 1.1880e+01 0.0000e+00]
 [2.0100e+03 8.0400e+00 0.0000e+00]
 [1.8960e+03 7.5840e+00 0.0000e+00]
 [1.5480e+03 6.1920e+00 0.0000e+00]
 [1.2033e+04 4.8132e+01 0.0000e+00]
 [3.0020e+03 1.2008e+01 0.0000e+00]
 [1.0320e+03 4.1280e+00 0.00

In [34]:

m3 = np.copy(m2)
for iy, ix in np.ndindex(m3.shape):
    m3[iy][ix] = m1[ix][0]/(m1[ix][1]+m2[iy][ix])
print(m3[2][:])
#np.savetxt('sample.csv', m3, delimiter=",")

[216.74961387 244.7096665  250.         245.18436984 243.94614491
 242.11394739 232.28206945 244.19899759 237.36981191 231.84647303
 235.50189793 247.94610582 240.58451341 246.08346911 237.65044009
 229.64169381 244.23830376 225.48250432 234.4217348  247.2599737
 246.86949637 242.84546198 241.00719424 235.50844651 231.89853191
 247.34490839 238.41795944 233.94287441 248.53812568 232.55164712
 238.23261464 247.80402108 229.21704958 238.89546935 228.47952157]


In [37]:

i = 28
T = 17*8
print(T)


136


In [38]:
def move_next_node(i):
    print("Agent is at " + str(i))
    global T
    j=i
    print("Agent have " + str(T))
    T = T - (m1[i][1] + m2[i][j])
    m1[i][2]=1
    print("Agent have " + str(T))
    j = find_best_node(i)
#     print("j:" + str(j))
    if T - (m2[i][j] + m1[j][1]) >= 0:
        print("moving to next node")
        print((m2[i][j] + m1[j][1]))
        move_next_node(j)
    else:
        print("time left"+str(T))
        
def find_best_node(i):
#  temp=np.copy(m3[i][:])
#     print("entered")
    print(np.amax(m3[i][:]))
    tempindex = np.argmax(m3[i][:])
    print("tempindex: " + str(tempindex))
    m3[i][tempindex] = 0.000
    secondhighest = np.argmax(m3[i][:])
#     print("second high " + str(secondhighest))
    if m1[secondhighest][2]==1:
        find_best_node(i)
        
    return secondhighest
    #bestnode = m3[i][secondhighest]
    #bestnode = m3[i][temp-1]

i=28
move_next_node(i)

Agent is at 28
Agent have 136
Agent have 84.99600000000001
247.48601309101548
tempindex: 19
moving to next node
51.31333333333333
Agent is at 31
Agent have 84.99600000000001
Agent have 34.21600000000001
250.0
tempindex: 31
time left34.21600000000001
